### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by lorencogonzaga** [hackiftekhar/IQAudioRecorderController#1]
Hi there!

First congrats for the project, really nice!

It is possible to configure this project to upload the audio files to Parse.com ?
Could you implement it or give any direction/tip ? 

Thnx and cheerz

**Comment by hackiftekhar** [comment]
You've to write the logic manually to upload it to parse.com. From the library side, when you click done, you'll get a temporary file path on it's delegate where the audio is saved.
