### ISSUE TITLE
Not able to get audio

### ISSUE THREAD

**Issue by guilhermefmbatista** [hackiftekhar/IQAudioRecorderController#10]
Hi!
First I would like to say that your library is fantastic, congratulations.
Second I´m having an issue that I can´t create a NSData from the filepath because NSData is always getting nil. Could you help me out?
Below is my code

-(void)audioRecorderController:(IQAudioRecorderController *)controller didFinishWithAudioAtPath:(NSString *)filePath
{
    //_audioFilePath = filePath;

```
NSURL *url = [NSURL URLWithString:filePath];
NSData *audioData = [NSData dataWithContentsOfURL:url]; //NSData is always getting nil
```

}

**Comment by hackiftekhar** [comment]
filePath contains local file path, so you should use 'fileURLWithPath:' method of NSURL instead of 'URLWithString:' method.
