### ISSUE TITLE
Could you make the tints settable?  

### ISSUE THREAD

**Issue by jeffreyjackson** [hackiftekhar/IQAudioRecorderController#12]
Id like the ability for custom tints please, can i make a PR for this?

**Comment by hackiftekhar** [comment]
Could you please let me know what you want to achieve?

**Comment by jeffreyjackson** [comment]
essentially all of the BLUE controls i want to change to a unique color

**Comment by jeffreyjackson** [comment]
BLUE controls and waveform i want to be a specific color

**Comment by hackiftekhar** [comment]
Sure! Please make a pull request.

**Comment by jeffreyjackson** [comment]
I've created a pull request for this.  if you accept the PR, would you also care to update the podspec version also?  thank you!

**Comment by hackiftekhar** [comment]
Just accepted

**Comment by jeffreyjackson** [comment]
thank you!  could you update the pod version too?

**Comment by hackiftekhar** [comment]
Will do when get some time.

**Comment by hackiftekhar** [comment]
Updated pod version for you.

**Comment by jeffreyjackson** [comment]
thanks!
