### ISSUE TITLE
Can't specify file format.

### ISSUE THREAD

**Issue by Ying1986** [hackiftekhar/IQAudioRecorderController#16]
Hello @hackiftekhar 

How are you?

Your library is simple and useful.
I think it will be better if you add to specify audio file format.
Current, it is only possible to record for m4a, but I need mp3.

I have seen your code, it can modify myself, but I want to use your library if possible.

Thank you.

**Comment by sebastianludwig** [comment]
That would be possible with #11 and is with my fork.

**Comment by hackiftekhar** [comment]
It looks like, according to this link you can't encode mp3 with iOS SDK:-
http://stackoverflow.com/a/6274188/1582217

It is a proprietary format when it comes to encoding:-
http://stackoverflow.com/a/10553363/1582217

**Comment by Focus848** [comment]
Hi~ @sebastianludwig 
I use your library, i need a mp3 format audio file.
I set the `format` property of IQAudioRecorder to "mp3" in `init` method of IQAudioRecorder,when my app launch,i get an error and the delegate method(`- (void)audioRecorderViewController:
                   didFailWithError:`) was called.

**Error information**:`The operation coulndn't be completed.(OSStatus error 1718449215)`

Please help me @sebastianludwig

**Comment by hackiftekhar** [comment]
You can read mp3 files with iOS SDK but you can't encode mp3 format with iOS SDK. It's propriety format of Microsoft when it comes to encoding.

**Comment by sebastianludwig** [comment]
However a quick Google search will yield some results on how you can transcode your recording to mp3.

**Comment by Focus848** [comment]
Thanks all!
