### ISSUE TITLE
recording length

### ISSUE THREAD

**Issue by nelzaatari** [hackiftekhar/IQAudioRecorderController#17]
it would be greate if we can specify the maximum recording time allowed in seconds when the controller stops recording by itself, it will make it perfect i guess with many uses

**Comment by hackiftekhar** [comment]
I'm working on the same thing. This feature will be available soon.

**Comment by hackiftekhar** [comment]
You can check, now there is a property `maximumRecordDuration`.

**Comment by nelzaatari** [comment]
awesome !!

**Comment by jingle30101** [comment]
> You can check, now there is a property `maximumRecordDuration`.

Hello, is this code for Audio recorder? where can I see the code, please? thanks.
