### ISSUE TITLE
convert m4a to mp3

### ISSUE THREAD

**Issue by Focus848** [hackiftekhar/IQAudioRecorderController#21]
I've searched through all the internet and didn't find a clear answer on my question 
 How do you record an m4a file  and later convert it to mp3?

**Comment by asfdfdfd** [comment]
You should use external encoding library. LAME for example.

**Comment by hackiftekhar** [comment]
It looks like, according to this link you can't encode mp3 with iOS SDK:-
http://stackoverflow.com/a/6274188/1582217

It is a proprietary format when it comes to encoding:-
http://stackoverflow.com/a/10553363/1582217

**Comment by hackiftekhar** [comment]
Duplicate of #16
