### ISSUE TITLE
Navigation bar and bottom toolbar doesn't appear.

### ISSUE THREAD

**Issue by DimonDeveloper** [hackiftekhar/IQAudioRecorderController#24]
Do this:
`IQAudioRecorderViewController *controller = [[IQAudioRecorderViewController alloc] init];
    controller.delegate = self;
    controller.allowCropping = YES;
    controller.barStyle = UIBarStyleBlackTranslucent;
    controller.normalTintColor = [UIColor whiteColor];
    controller.highlightedTintColor = [UIColor colorWithRed:0.0523 green:0.6438 blue:1.0 alpha:1.0];
    dispatch_async(dispatch_get_main_queue(), ^ {
        [self presentViewController:controller animated:YES completion:nil];
    });`

I'm using code from github, not from podsec.

Got this:
![img_0178](https://cloud.githubusercontent.com/assets/3527457/15186957/c47b7e68-17a7-11e6-8cda-3ff569525f54.PNG)

**Comment by hackiftekhar** [comment]
You should use `presentAudioRecorderViewControllerAnimated` or `presentBlurredAudioRecorderViewControllerAnimated` method to present `IQAudioRecorderViewController`.

**Comment by DimonDeveloper** [comment]
Oh right, now everything ok! :). Thank you.
