### ISSUE TITLE
Crash while present "Delete recording" alert if IQAudioRecorderController is presented modally

### ISSUE THREAD

**Issue by AlexandrTerentyev** [hackiftekhar/IQAudioRecorderController#25]
Logs contain next message: Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x7ed34f20>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.

**Comment by hackiftekhar** [comment]
Your Pull request is merged. Thanks!
