### ISSUE TITLE
Microphone icon is not displayed

### ISSUE THREAD

**Issue by CrazyWisdom** [hackiftekhar/IQAudioRecorderController#31]
Microphone icon is not displayed

My code:

```
    func audioRecordAction() {
        let audioRecorderController = IQAudioRecorderController()
        audioRecorderController.delegate = self
        audioRecorderController.title = "Audio Recorder"
        audioRecorderController.barStyle = UIBarStyle.BlackOpaque
        presentViewController(audioRecorderController, animated: true, completion: nil)
    }
```

**Comment by rcholic** [comment]
yes, I had the same problem. I imported the image sets as found in this library to my app, the microphone/record/play icons show up correctly.

**Comment by DuncanACampbell** [comment]
Same happened to me.  Seemed to occur once I started using the use_frameworks! flag in the podfile.

**Comment by githubdoramon** [comment]
Each barStyle seems to show some different combination of stuff

**Comment by hackiftekhar** [comment]
Do you guys find out why sometimes icon doesn't appear so that I can fix it?

**Comment by awaisemaan** [comment]
You guys need to use 'presentAudioRecorderViewControllerAnimated' instead of using 'presentViewController' as you can clearly see these methods in documentation.
