### ISSUE TITLE
property 'maximumRecordDuration' is not available to IQAudioRecorderController in Swift

### ISSUE THREAD

**Issue by rcholic** [hackiftekhar/IQAudioRecorderController#33]
I am using this library in my Swift 2.2-based app, and it works beautifully, however, I found the property `maximumRecordDuration` is not available for an instance of IQAudioRecorderController to use. 

I am wondering if it is possible to use `maximumRecordDuration` for Swift-based app. Thanks!

**Comment by hackiftekhar** [comment]
I don't think it should be an issue and it should work fine. Don't know why you are getting issues.

**Comment by rcholic** [comment]
@hackiftekhar thanks for the reply.
In my briding header file, I imported this library as:

```
#import <IQAudioRecorderController/IQAudioRecorderController.h>
```

When I create an instance of IQAudioRecorderController in my Swift-based view controller, I cannot add maximumRecordDuration property to this instance. Is my way of importing this library wrong? thanks

**Comment by sssionggg** [comment]
@rcholic you need to use the github version instead the one from cocoapods.

```
pod 'IQAudioRecorderController', git: 'https://github.com/hackiftekhar/IQAudioRecorderController'
```

@hackiftekhar probably a good idea to update the version on github pretty soon?

**Comment by hackiftekhar** [comment]
I'm planning to update it soon. Thanks @siong1987

**Comment by rcholic** [comment]
@siong1987 thanks for the info, but I've created basically a clone project of this at here https://github.com/rcholic/SwiftySoundRecorder  (or `pod install SwiftySoundRecorder`), my library pretty much does the same thing, but readily allows using `maxDuration` for recording, and it is in Swift 2.2. 

If I knew the trick of installing this library by the git commit, I wouldn't have spent time writing up my own copy of the library :)

**Comment by hackiftekhar** [comment]
Updated CocoaPods
