### ISSUE TITLE
crop operation is hard to do

### ISSUE THREAD

**Issue by hqlulu** [hackiftekhar/IQAudioRecorderController#35]
it is hard to move the end or start line

**Comment by hackiftekhar** [comment]
Can you figure-out and make the changes and send a pull-request please? I'm going through a tight schedule these days.

**Comment by niravghori** [comment]
Does any one have figure - out this issue, so please share code here and kindly needed to me.

**Comment by Saad-Umar** [comment]
Facing the same, the cropping selectors (left right) are not easily tappable when they in the corners, any update on this issue yet?

**Comment by hackiftekhar** [comment]
@niravghori @Saad-Umar can one of you fix this and make a pull-request?
