### ISSUE TITLE
How to increase the recording volume ?

### ISSUE THREAD

**Issue by maximilienandile** [hackiftekhar/IQAudioRecorderController#36]
First of all, **thanks** for your amazing work !

I would like to be able to **increase the volume of recording**. Is there a way to do it directly inside the application ?
Which **file** is handling the recording volume of the microphone (if there is one) ?

I would appreciate any tips !

Thanks for your answer.

**Comment by hackiftekhar** [comment]
I'll check and will let you know my feedback.

**Comment by hackiftekhar** [comment]
@maximilienandile  I checked and found that there is no way to increase the volume of recording. sorry!
