### ISSUE TITLE
IQAudioRecorderViewController.h isn't generated

### ISSUE THREAD

**Issue by Sachin-Raut** [hackiftekhar/IQAudioRecorderController#39]
After installing pod, following files are not generated.

IQAudioRecorderViewController.h 
IQAudioRecorderViewController.m

Is there any issue? thanks

**Comment by hackiftekhar** [comment]
I don't think this is an issue because it's generating at my end and you are the only one who is getting this issue. So this might be more related to your configuration or your project configuration issue.

**Comment by Sachin-Raut** [comment]
Hi thanks for your reply.
Its working fine since last few days. 
But there was an issue & few of my friends had also experienced this issue couple of months ago.

By the way great lib. Thanks a lot.
