### ISSUE TITLE
Problem in opening the trim view controller for an existing audio

### ISSUE THREAD

**Issue by credo92** [hackiftekhar/IQAudioRecorderController#46]
Getting repeatedly error : IQ_FDWaveformView could not load asset: The requested URL was not found on this server.
// Using a button to call function cropAction with the url of the media Item

@IBAction func crop(_ sender: Any) {
        
        cropAction("file:///private/var/mobile/Containers/Data/Application/97E1CAB1-661A-477A-9CCE-C8CFED70E309/tmp/E04AA047-BCA2-4DC7-A53F-D6591D9A8DFB.m4a"!)
    }

    func cropAction(_ item: Any) {
        //    let controller = IQAudioCropperViewController(filePath: item as! String)
        let controller = IQAudioCropperViewController.init(filePath: item as! String)
        
        controller.delegate = self
        controller.title = "Edit"
        controller.barStyle = UIBarStyle.default
        
        controller.normalTintColor = UIColor.magenta
        controller.highlightedTintColor = UIColor.orange;
        
        
        presentBlurredAudioCropperViewControllerAnimated(controller)
    }
    
    func audioCropperController(_ controller: IQAudioCropperViewController, didFinishWithAudioAtPath filePath: String) {
        //Do your custom work with file at filePath.
        controller.dismiss(animated: true) { _ in }
    }
    
    func audioCropperControllerDidCancel(_ controller: IQAudioCropperViewController) {
        //Notifying that user has clicked cancel.
        controller.dismiss(animated: true) { _ in }
    }

**Comment by hackiftekhar** [comment]
Looks like thus is not the path your app expect. When we install one app over another then the unique bundle string change. So the requested url cannot be found at hardcoded path. You should get tge temporary folder path using NSTemporaryDirectory() method.

**Comment by credo92** [comment]
I Did That but it still doesn't work  :(
I query the local songs, export them to a temp file using export function, 
then call cropAction using an IBACTION, cropAction is passed the temporary url that gets created. PLEASE HELP. 

class ViewController: UIViewController , IQAudioCropperViewControllerDelegate{
    var data		: [MPMediaItem]	= []
    var file : String? = nil

    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        // Query the Pre-Existing Audio
        let tempData = MPMediaQuery.songs().items ?? []
        self.data = []
        for mediaItem in tempData {
            if (mediaItem.isCloudItem == false && mediaItem.assetURL != nil) {
                print(mediaItem.assetURL)
                // get title for bpm
                print(mediaItem.title)
                print(mediaItem.playbackDuration)
                self.data.append(mediaItem)
            }
        }
        
        var data2 : MPMediaItem = data[0]
        print(data2.playbackDuration)
        print("BEATS PER MINUTE +\(data2.beatsPerMinute)")
        exampleUsage(with: data2)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // EXPORTING PREXISTING INTO AN TEMP DIRECTORY

    func export(_ assetURL: URL, completionHandler: @escaping (_ fileURL: URL?, _ error: Error?) -> ()) {
        let asset = AVURLAsset(url: assetURL)
        guard let exporter = AVAssetExportSession(asset: asset, presetName: AVAssetExportPresetAppleM4A) else {
            completionHandler(nil, ExportError.unableToCreateExporter)
            return
        }
        
        let fileURL = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent(NSUUID().uuidString)
            .appendingPathExtension("m4a")
                
        exporter.outputURL = fileURL
        exporter.outputFileType = AVFileTypeAppleM4A
        
        exporter.exportAsynchronously {
            if exporter.status == .completed {
                completionHandler(fileURL, nil)
            } else {
                completionHandler(nil, exporter.error)
            }
        }
    }
    
    // Calling export function 
    func exampleUsage(with mediaItem: MPMediaItem) {
        if let assetURL = mediaItem.assetURL {
            export(assetURL) { fileURL, error in
                guard let fileURL = fileURL, error == nil else {
                    print("export failed: \(error)")
                    return
                }
                
                // use fileURL of temporary file here
                print("\(fileURL)")
        
                self.file = String(describing:fileURL)

            }
        }
    }
    
    enum ExportError: Error {
        case unableToCreateExporter
    }
    
    
   // CROP TEST
    
    @IBAction func crop(_ sender: Any) {
       
        cropAction(String(describing:self.file))
 
    }
    // crop
    func cropAction(_ item: Any) {
        //    let controller = IQAudioCropperViewController(filePath: item as! String)
        let controller = IQAudioCropperViewController.init(filePath: item as! String)
        
        controller.delegate = self
        controller.title = "Edit"
        controller.barStyle = UIBarStyle.default
        
        controller.normalTintColor = UIColor.magenta
        controller.highlightedTintColor = UIColor.orange;
        
        
        presentBlurredAudioCropperViewControllerAnimated(controller)
    }
    
    func audioCropperController(_ controller: IQAudioCropperViewController, didFinishWithAudioAtPath filePath: String) {
        //Do your custom work with file at filePath.
        controller.dismiss(animated: true) { _ in }
    }
    
    func audioCropperControllerDidCancel(_ controller: IQAudioCropperViewController) {
        //Notifying that user has clicked cancel.
        controller.dismiss(animated: true) { _ in }
    }



}

**Comment by hackiftekhar** [comment]
Look carefully. You are converting your URL to string using this code `self.file = String(describing:fileURL)` but instead of URL to string you should convert it to path using `fileURL.path`, please have a look at this answer https://stackoverflow.com/a/8082770.

**Comment by credo92** [comment]
Still getting the same error. I get a path for existing MPMediaItems as /item.4a .

+ Will it be possible to integrate or give a sample demo for TRIMMING an existing audio file ? (Retrieved through MPMediaQuery.songs().items )

**Comment by credo92** [comment]
//
//  ViewController.swift
//  trim4
//
//  Created by Vipul Srivastav on 2017-08-19.
//  Copyright © 2017 Vipul Srivastav. All rights reserved.
//

import UIKit
import AVKit
import AVFoundation
import MediaPlayer
import IQAudioRecorderController



class ViewController: UIViewController , IQAudioCropperViewControllerDelegate{
    var data		: [MPMediaItem]	= []
     var data2		: MPMediaItem? = nil
//    var file : String? = nil
    var asset: AVAsset? = nil
    var avPlayer: AVPlayer!
    
    var fileURL = URL(fileURLWithPath: NSTemporaryDirectory())
        .appendingPathComponent(NSUUID().uuidString)
        .appendingPathExtension("m4a")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let tempData = MPMediaQuery.songs().items ?? []
        self.data = []
        for mediaItem in tempData {
            if (mediaItem.isCloudItem == false && mediaItem.assetURL != nil) {
                print(mediaItem.assetURL?.path)
                // get title for bpm
                print(mediaItem.title)
                print(mediaItem.playbackDuration)
                self.data.append(mediaItem)
            }
        }
        
         data2  = data[1]
        
        print(data2?.playbackDuration)
        print("BEATS PER MINUTE +\(data2?.beatsPerMinute)")
        exampleUsage(with: data2!)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func export(_ assetURL: URL, completionHandler: @escaping (_ fileURL: URL?, _ error: Error?) -> ()) {
        let asset = AVURLAsset(url: assetURL)
        guard let exporter = AVAssetExportSession(asset: asset, presetName: AVFileTypeAppleM4A) else {
            completionHandler(nil, ExportError.unableToCreateExporter)
            return
        }
        
        let fileURL = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent(NSUUID().uuidString)
            .appendingPathExtension("m4a")
        
//        let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
//        let fileURL = documentsDirectory.appendingPathComponent("test2.m4a")
        
//       if let url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: ".m4a"){
//            //var cachesURL = url.URLByAppendingPathComponent("Library", isDirectory:  true)
//            var cachesURL = url.appendingPathComponent("Library", isDirectory: true)
//            cachesURL = url.appendingPathComponent("Caches", isDirectory:  true)
//        }
//        let startTime = CMTimeMake(40, 1)
//        let stopTime = CMTimeMake(55,1)
//        let exportTimeRange = CMTimeRangeFromTimeToTime(startTime, stopTime)
//        print(exportTimeRange)
//        exporter.timeRange = exportTimeRange
//        print(exporter.timeRange)
        
        exporter.outputURL = fileURL
//        exporter.outputFileType = AVFileTypeAppleM4A
        
        exporter.outputFileType = AVFileTypeAppleM4A
        
        exporter.exportAsynchronously {
            if exporter.status == .completed {
                completionHandler(fileURL, nil)
            } else {
                completionHandler(nil, exporter.error)
            }
        }
    }
    
    func exampleUsage(with mediaItem: MPMediaItem) {
        if let assetURL = mediaItem.assetURL {
            export(assetURL) { fileURL, error in
                guard let fileURL = fileURL, error == nil else {
                    print("export failed: \(error)")
                    return
                }
                
                // use fileURL of temporary file here
                print("\(fileURL)")
                
//                self.fileURL = String(describing:fileURL)
                
                print("self. file +\(self.fileURL)")
                
                print("fileUrl isFileURL + \(fileURL.isFileURL)")
                
                print("fileURL absoulteString+ \(fileURL.absoluteString)")
                
                print("fileURL path + \(fileURL.path)")
                
              self.asset = AVAsset.init(url: fileURL)
                
                print(self.asset?.isPlayable)
                print(self.asset?.duration.seconds)
               
                print(self.asset?.isReadable)
                
                //print("self.data2.assetURL + \(self.data2?.assetURL?.path)")
            }
        }
    }
    
    enum ExportError: Error {
        case unableToCreateExporter
    }
    
    
    
    @IBAction func play(_ sender: Any) {
        play()
        
    }
    
    func play() {
        
        let urll : URL = fileURL
        print("PLAY + \(urll)")
        
       // let avasset2 = AVAsset.init(url: urll)
        

        
        //let avplayeritem2 = AVPlayerItem.init(asset: avasset2)
    
//         self.avPlayer = AVPlayer.init(playerItem: avplayeritem2)
        
        self.avPlayer = AVPlayer.init(url: urll)
    
        print("About to play")
        self.avPlayer.play()
        
        
        

        
    }
    
    
   // CROP TEST
    
    @IBAction func crop(_ sender: Any) {
       
        cropAction(fileURL.path)
       
        
    }
    // crop
    func cropAction(_ item: Any) {
        

//        let controller = IQAudioCropperViewController(filePath:  fileURL.path )
        let controller = IQAudioCropperViewController(filePath:  (self.data2?.assetURL?.path)! )
        controller.delegate = self
        controller.title = "Edit"
        controller.barStyle = UIBarStyle.default
        
        controller.normalTintColor = UIColor.magenta
        controller.highlightedTintColor = UIColor.orange;
        
        
        presentBlurredAudioCropperViewControllerAnimated(controller)
    }
    
    func audioCropperController(_ controller: IQAudioCropperViewController, didFinishWithAudioAtPath filePath: String) {
        //Do your custom work with file at filePath.
        controller.dismiss(animated: true) { _ in }
    }
    
    func audioCropperControllerDidCancel(_ controller: IQAudioCropperViewController) {
        //Notifying that user has clicked cancel.
        controller.dismiss(animated: true) { _ in }
    }



}

**Comment by hackiftekhar** [comment]
hmm, okay, it's a great idea to add cropping demo. Will do.

**Comment by credo92** [comment]
Solved! Thanks so much!!, 

+ Although i am still not able to Crop the##  **_pre-exisinting .m4a Local MpMedia Items._**  retrieved through ## **_MPMediaQuery.songs().items_** 

+ Because i think i tried to export the ## **_exisitng .m4a as a .m4a temp file using the exporter.outfileType/Preset as AVFileTypeAppleM4A._** may be thats why i was facing the problem

+ It worked for mp3! 

+ Amyway Please update the doc in the near future for cropping .m4a exisitng audio file ! thanks @hackiftekhar
