### ISSUE TITLE
IQAudioCropperController sometimes can't open

### ISSUE THREAD

**Issue by J8rry** [hackiftekhar/IQAudioRecorderController#50]
when you already have a record,  then if you click the CropButton in the Demo frequently, it will stay the loadingView and never appear the FDWaveformView;
![record_issue2](https://user-images.githubusercontent.com/16513132/33869793-bfc5469e-df45-11e7-9207-92fa32f31a16.gif)

**Comment by J8rry** [comment]
IQ_FDWaveformView.h   
 - (void)layoutSubviews { }
I think some code should not put in this method, cause you can't know when Apple will call this method;

**Comment by paywithbolt** [comment]
Its because IQ_FDWaveformView:367 requires strong references in the block, ie:

   ```
 IQ_FDWaveformView * _self = self;
    
    [IQ_FDWaveformView sliceAndDownsampleAsset:self.asset track:self.assetTrack startSamples:renderStartSamples endSamples:renderEndSamples targetSamples:widthInPixels done:^(NSData *samples, NSInteger sampleCount, Float32 sampleMax) {
        
        [_self plotLogGraph:samples
              maximumValue:sampleMax
              mimimumValue:noiseFloor
               sampleCount:sampleCount
               imageHeight:heightInPixels
                      done:^(UIImage *image,
                             UIImage *selectedImage,
                             UIImage *cropImage) {
                          dispatch_async(dispatch_get_main_queue(), ^{
                              _self.image.image = image;
                              _self.highlightedImage.image = selectedImage;
                              _self.croppedImage.image = cropImage;
                              _self.cachedStartSamples = renderStartSamples;
                              _self.cachedEndSamples = renderEndSamples;
                              _self.renderingInProgress = NO;
                              [_self layoutSubviews]; // warning
                              if ([_self.delegate respondsToSelector:@selector(waveformViewDidRender:)])
                                  [_self.delegate waveformViewDidRender:_self];
                          });
                      }
         ];
    }];
```

**Comment by Pradiptamldt** [comment]
Can't crop after cropping 2 times same audio file. At IQ_FDWaveformView.m class there is a variable zoomEndSamples which is assigned from - (void)setZoomEndSamples:(long)endSamples method, it gets 0 after 2 times crop. Please help how to solve that.

**Comment by hackiftekhar** [comment]
Please try using v1.2.3. I've released a new version with this fix.

**Comment by Pradiptamldt** [comment]
Can you please give the link, I can't find that link.

**Comment by hackiftekhar** [comment]
It's released via cocoapods and I believe you know about how to install it.

**Comment by Pradiptamldt** [comment]
I have updated my pod file. Few things changes, but still I can't crop audio more than 2-3 times. After third attempt the loader is spinning non stopping.

**Comment by hackiftekhar** [comment]
Are you sure you are using v1.2.3?

**Comment by Pradiptamldt** [comment]
yes it was showing that version.

**Comment by Pradiptamldt** [comment]
If I crop for third time that wave either gone completely or it's fluctuating very fast with activity indicator which doesn't allow me set crop range. Please tell me how to fix that, need urgent help.

**Comment by hackiftekhar** [comment]
I'll try to check when got some free time.
