### ISSUE TITLE
How can i decrease the waveform Height 

### ISSUE THREAD

**Issue by sohilmultani** [hackiftekhar/IQAudioRecorderController#52]
when i record audio using IQAudioRecorderViewController the wave are outside the screen how can i decrease waveform height when audio is High.

**Comment by hackiftekhar** [comment]
Hmm, which version of library are you using?

**Comment by sohilmultani** [comment]
i don't know which version i used but its old 6 month

**Comment by hackiftekhar** [comment]
Can you please try the latest version of library because I fixed something like this couple of weeks ago.

**Comment by sohilmultani** [comment]
Thanks For Replay. it is fixed now.

**Comment by seemanraj** [comment]
> Can you please try the latest version of library because I fixed something like this couple of weeks ago.

Im using the latest one can we decrease the wave height because i just need a height to be constant. its overlapping my texts
