### ISSUE TITLE
audio duration silider

### ISSUE THREAD

**Issue by EgzonArifi** [hackiftekhar/IQAudioRecorderController#54]
I'm using IQAudioRecorderController on a swift project like this:
```
 let controller = IQAudioRecorderViewController()
 controller.delegate = self
 controller.allowCropping = false
 controller.barStyle = UIBarStyle.black
 self.presentBlurredAudioRecorderViewControllerAnimated(controller)
```
But I have a problem while playing recorded audio, it looks like that:

![screen shot 2018-04-22 at 4 19 26 pm](https://user-images.githubusercontent.com/7537706/39095964-4c52f448-4649-11e8-8bca-a642eccbe71c.png)

Does somebody had this problem?
Thank you

**Comment by EgzonArifi** [comment]
Ah, I see PR #53 :(

**Comment by zeevmindali** [comment]
how you make it work in swift? I done all but keep getting err of init

**Comment by hackiftekhar** [comment]
I need to check swift compatibility

**Comment by EgzonArifi** [comment]
@zeevmindali I didn't have problems to use it in swift.
@hackiftekhar Why you don't merge #53 ?

**Comment by hackiftekhar** [comment]
Merged now!
