### ISSUE TITLE
support for swift

### ISSUE THREAD

**Issue by zeevmindali** [hackiftekhar/IQAudioRecorderController#57]
can I use your awesome library in swift?

**Comment by hackiftekhar** [comment]
Probably yes, you can give a try.

**Comment by githubdoramon** [comment]
It works out of the box with Swift

**Comment by JustinJusz** [comment]
Not working in swift

**Comment by bscarano** [comment]
Put ```#import <IQAudioRecorderController/IQAudioRecorderViewController.h>``` into your bridging header and it will work in Swift
