### ISSUE TITLE
Duplicate Symbol

### ISSUE THREAD

**Issue by pjebs** [hackiftekhar/IQAudioRecorderController#9]
I noticed that your cocoapod includes: SCSiriWaveformView

Can you please removed the SCSiriWaveformView.h and SCSiriWaveformView.m files 
and incorporate SCSiriWaveformView pod as a dependency of your IQAudioRecorderController pod.

That way other I can use SCSiriWaveformView without the compiler not working and stating Duplicate Symbol errors.

**Comment by hackiftekhar** [comment]
You're right. I have to add a dependency with SCSiriWaveformView. Will do.

**Comment by hackiftekhar** [comment]
Updated to v1.0.1 and now adding SCSiriWaveformView as dependency.
